version: "3"

services:
  app:
    build: .
    container_name: bun-user-api
    volumes:
      - .:/bun/src/
    ports:
      - "3000:3000"
  database:
    container_name: bun-user-database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bun-user
    ports:
      - '5432:5432'
    volumes: 
      - ./.docker/postgres:/var/lib/postgresql/data